import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "next-themes";
import WrapperPage from "@/components/layout/wrapper-page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`
          h-dvh
          antialiased
          bg-background 
          overscroll-none
          select-none
          selection:bg-foreground
          selection:text-background
          ${inter.className}
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WrapperPage>
            <main className="max-w-screen-2xl mx-auto h-full">{children}</main>
          </WrapperPage>
        </ThemeProvider>
      </body>
    </html>
  );
}
